---
- name: Install Docker.
  yum:
    name: docker
    state: present
    update_cache: true

- name: Start Docker.
  service:
    name: docker
    state: started

- name: Enable Docker.
  service:
    name: docker
    enabled: yes

- name: Add Kubernetes YUM Repository.
  yum_repository:
   name: Kubernetes
   description: Kubernetes YUM repository
   baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
   gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
   gpgcheck: yes

- name: Install kubelet.
  yum:
     name: kubelet-1.15.1
     state: present
     update_cache: true

- name: Install kubeadm.
  yum:
     name: kubeadm-1.15.1
     state: present

- name: Start kubelet.
  service:
    name: kubelet
    enabled: yes
    state: started

- name: Install kubectl.
  yum:
     name: kubectl-1.15.1
     state: present
     allow_downgrade: yes

- name: Initialize the Cluster.
  shell: kubeadm init --ignore-preflight-errors=NumCPU --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt
  args:
    chdir: $HOME
    creates: cluster_initialized.txt

- name: Create .kube directory.
  become: yes
  become_user: centos
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755

- name: Copy admin.conf to user's kube config.
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/centos/.kube/config
    remote_src: yes
    owner: centos

- name: Install Pod Network.
  become: yes
  become_user: centos
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/a70459be0084506e4ec919aa1c114638878db11b/Documentation/kube-flannel.yml >> pod_network_setup.txt
  args:
    chdir: $HOME
    creates: pod_network_setup.txt
